-- ============================================================
-- Flyway Migration V6: Create Transaction Table
-- ============================================================
-- Replaces: TRANSACT VSAM KSDS file
-- Copybook: CVTRA05Y.cpy (TRAN-RECORD, 350 bytes)
-- FILLER:   20 bytes excluded (padding only, no business data)
--
-- 13 data fields mapped from COBOL PIC clauses to PostgreSQL types.
-- Transaction ID is generated by transaction_id_seq (V1 migration).
--
-- Programs: COTRN00C (List), COTRN01C (View), COTRN02C (Add)
-- Business Rules: All BR-LT-*, BR-VT-*, BR-AT-* rules reference this table.
--
-- VSAM Access Patterns Replaced:
--   CT00 List: STARTBR + READNEXT/READPREV → SELECT ... ORDER BY ... LIMIT/OFFSET
--   CT01 View: READ by TRAN-ID → SELECT ... WHERE transaction_id = ?
--   CT02 Add:  WRITE TRANSACT → INSERT INTO transaction VALUES (...)
--   CT02 ID Gen: STARTBR HIGH-VALUES + READPREV → nextval('transaction_id_seq')
-- ============================================================

CREATE TABLE transaction (
    -- PK: TRAN-ID X(16) — 16-character transaction identifier
    -- Generated by: LPAD(nextval('transaction_id_seq')::TEXT, 16, '0')
    -- Business Rule: BR-AT-13 (auto-increment), BR-AT-14 (duplicate rejection)
    transaction_id      VARCHAR(16)     NOT NULL,

    -- FK: TRAN-CARD-NUM X(16) → card.card_number
    -- Resolved during CT02 Add via cross-reference (BR-AT-04, BR-AT-05)
    card_number         VARCHAR(16)     NOT NULL,

    -- TRAN-TYPE-CD X(02) — validated as numeric in Phase 3 (BR-AT-07)
    type_code           VARCHAR(2)      NOT NULL,

    -- TRAN-CAT-CD 9(04) — validated as numeric in Phase 3 (BR-AT-07)
    category_code       NUMERIC(4, 0)   NOT NULL,

    -- TRAN-SOURCE X(10) — mandatory field (BR-AT-06)
    source              VARCHAR(10)     NOT NULL,

    -- TRAN-DESC X(100) — mandatory field (BR-AT-06)
    description         VARCHAR(100)    NOT NULL,

    -- TRAN-AMT S9(09)V99 — signed decimal, validated in Phase 4 (BR-AT-08)
    -- MUST use NUMERIC (never float/double) for financial precision
    amount              NUMERIC(11, 2)  NOT NULL,

    -- TRAN-MERCHANT-ID 9(09) — validated as numeric in Phase 6 (BR-AT-11)
    merchant_id         NUMERIC(9, 0)   NOT NULL,

    -- TRAN-MERCHANT-NAME X(50) — mandatory field (BR-AT-06)
    merchant_name       VARCHAR(50)     NOT NULL,

    -- TRAN-MERCHANT-CITY X(50) — mandatory field (BR-AT-06)
    merchant_city       VARCHAR(50)     NOT NULL,

    -- TRAN-MERCHANT-ZIP X(10) — mandatory field (BR-AT-06)
    merchant_zip        VARCHAR(10)     NOT NULL,

    -- TRAN-ORIG-TS X(26) — origination timestamp
    -- Validated in Phase 5: format YYYY-MM-DD (BR-AT-09) + calendar validity (BR-AT-10)
    origination_ts      TIMESTAMP       NOT NULL,

    -- TRAN-PROC-TS X(26) — processing timestamp
    -- Validated in Phase 5: format YYYY-MM-DD (BR-AT-09) + calendar validity (BR-AT-10)
    processing_ts       TIMESTAMP       NOT NULL,

    -- Constraints
    CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id),
    CONSTRAINT fk_transaction_card FOREIGN KEY (card_number)
        REFERENCES card (card_number)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

-- Index on card_number for FK lookups and "transactions by card" queries
CREATE INDEX idx_transaction_card_number ON transaction (card_number);

-- Table comment
COMMENT ON TABLE transaction IS
    'Transaction records. Replaces TRANSACT VSAM KSDS (CVTRA05Y.cpy, 350 bytes). 13 fields mapped; 20-byte FILLER excluded. Used by CT00 (List), CT01 (View), CT02 (Add).';

COMMENT ON COLUMN transaction.transaction_id IS 'TRAN-ID X(16) — PK, generated via transaction_id_seq. BR-AT-13, BR-AT-14.';
COMMENT ON COLUMN transaction.card_number IS 'TRAN-CARD-NUM X(16) — FK to card. Resolved via cross-reference. BR-AT-04, BR-AT-05.';
COMMENT ON COLUMN transaction.amount IS 'TRAN-AMT S9(09)V99 — Signed decimal (NUMERIC, never float). BR-AT-08.';
COMMENT ON COLUMN transaction.origination_ts IS 'TRAN-ORIG-TS X(26) — Validated: YYYY-MM-DD format + calendar validity. BR-AT-09, BR-AT-10.';
COMMENT ON COLUMN transaction.processing_ts IS 'TRAN-PROC-TS X(26) — Validated: YYYY-MM-DD format + calendar validity. BR-AT-09, BR-AT-10.';
