spring.datasource.url=jdbc:postgresql://localhost:5432/carddemo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=carddemo
spring.datasource.password=carddemo
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
