spring.datasource.url=jdbc:postgresql://postgres:5432/carddemo
spring.datasource.username=carddemo
spring.datasource.password=carddemo
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.enabled=true
jwt.secret=cardDemoSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong2024
jwt.expiration=86400000
