-- CardDemo Mainframe to Java Migration - Initial Schema
-- Migrated from VSAM KSDS files, DB2 tables, and IMS DB segments

-- =====================================================
-- Phase 1: Core VSAM File Tables
-- =====================================================

-- CUSTFILE -> customers (Copybook: CVCUS01Y, 500-byte FB records)
CREATE TABLE customers (
    cust_id                  BIGINT        NOT NULL PRIMARY KEY,
    cust_first_name          VARCHAR(25),
    cust_middle_name         VARCHAR(25),
    cust_last_name           VARCHAR(25),
    cust_addr_line_1         VARCHAR(50),
    cust_addr_line_2         VARCHAR(50),
    cust_addr_line_3         VARCHAR(50),
    cust_addr_state_cd       VARCHAR(2),
    cust_addr_country_cd     VARCHAR(3),
    cust_addr_zip            VARCHAR(10),
    cust_phone_num_1         VARCHAR(15),
    cust_phone_num_2         VARCHAR(15),
    cust_ssn                 BIGINT,
    cust_govt_issued_id      VARCHAR(20),
    cust_dob_yyyy_mm_dd      VARCHAR(10),
    cust_eft_account_id      VARCHAR(10),
    cust_pri_card_holder_ind VARCHAR(1),
    cust_fico_credit_score   INTEGER
);

-- ACCTFILE -> accounts (Copybook: CVACT01Y, 300-byte FB records)
CREATE TABLE accounts (
    acct_id                BIGINT        NOT NULL PRIMARY KEY,
    acct_active_status     VARCHAR(1),
    acct_curr_bal          DECIMAL(12,2),
    acct_credit_limit      DECIMAL(12,2),
    acct_cash_credit_limit DECIMAL(12,2),
    acct_open_date         VARCHAR(10),
    acct_expiration_date   VARCHAR(10),
    acct_reissue_date      VARCHAR(10),
    acct_curr_cyc_credit   DECIMAL(12,2),
    acct_curr_cyc_debit    DECIMAL(12,2),
    acct_addr_zip          VARCHAR(10),
    acct_group_id          VARCHAR(10)
);

-- CARDFILE -> cards (Copybook: CVACT02Y, 150-byte FB records)
CREATE TABLE cards (
    card_num              VARCHAR(16)   NOT NULL PRIMARY KEY,
    card_acct_id          BIGINT,
    card_cvv_cd           INTEGER,
    card_embossed_name    VARCHAR(50),
    card_expiration_date  VARCHAR(10),
    card_active_status    VARCHAR(1)
);

-- TRANSACT (VSAM KSDS with AIX on card number) -> transactions
-- (Copybook: CVTRA05Y, 350-byte FB records)
CREATE TABLE transactions (
    tran_id             VARCHAR(16)   NOT NULL PRIMARY KEY,
    tran_type_cd        VARCHAR(2),
    tran_cat_cd         INTEGER,
    tran_source         VARCHAR(10),
    tran_desc           VARCHAR(100),
    tran_amt            DECIMAL(11,2),
    tran_merchant_id    BIGINT,
    tran_merchant_name  VARCHAR(50),
    tran_merchant_city  VARCHAR(50),
    tran_merchant_zip   VARCHAR(10),
    tran_card_num       VARCHAR(16),
    tran_orig_ts        VARCHAR(26),
    tran_proc_ts        VARCHAR(26)
);
CREATE INDEX idx_tran_card_num ON transactions(tran_card_num);

-- XREFFILE -> card_account_xref (Copybook: CVACT03Y, 50-byte FB records)
CREATE TABLE card_account_xref (
    xref_card_num   VARCHAR(16)   NOT NULL PRIMARY KEY,
    xref_cust_id    BIGINT,
    xref_acct_id    BIGINT
);
CREATE INDEX idx_xref_acct_id ON card_account_xref(xref_acct_id);

-- USRSEC -> users (Copybook: CSUSR01Y, 80-byte FB records)
CREATE TABLE users (
    usr_id      VARCHAR(8)    NOT NULL PRIMARY KEY,
    usr_fname   VARCHAR(20),
    usr_lname   VARCHAR(20),
    usr_pwd     VARCHAR(8),
    usr_type    VARCHAR(1)
);

-- DISCGRP.PS -> disclosure_groups (Copybook: CVTRA02Y, 50-byte FB records)
CREATE TABLE disclosure_groups (
    dis_acct_group_id   VARCHAR(10)   NOT NULL,
    dis_tran_type_cd    VARCHAR(2)    NOT NULL,
    dis_tran_cat_cd     INTEGER       NOT NULL,
    dis_int_rate        DECIMAL(6,2),
    PRIMARY KEY (dis_acct_group_id, dis_tran_type_cd, dis_tran_cat_cd)
);

-- TRANCATG.PS -> transaction_categories (Copybook: CVTRA04Y, 60-byte FB records)
CREATE TABLE transaction_categories (
    tran_type_cd        VARCHAR(2)    NOT NULL,
    tran_cat_cd         INTEGER       NOT NULL,
    tran_cat_type_desc  VARCHAR(50),
    PRIMARY KEY (tran_type_cd, tran_cat_cd)
);

-- TRANTYPE.PS -> transaction_types (Copybook: CVTRA03Y, 60-byte FB records)
CREATE TABLE transaction_types (
    tran_type       VARCHAR(2)    NOT NULL PRIMARY KEY,
    tran_type_desc  VARCHAR(50)
);

-- TCATBALF.PS -> transaction_category_balances (Copybook: CVTRA01Y, 50-byte FB records)
CREATE TABLE transaction_category_balances (
    trancat_acct_id   BIGINT        NOT NULL,
    trancat_type_cd   VARCHAR(2)    NOT NULL,
    trancat_cd        INTEGER       NOT NULL,
    tran_cat_bal      DECIMAL(11,2),
    PRIMARY KEY (trancat_acct_id, trancat_type_cd, trancat_cd)
);

-- =====================================================
-- Phase 1: Optional Module - IMS DB (Authorization)
-- =====================================================

-- IMS root segment PAUTSUM0 -> auth_summary
CREATE TABLE auth_summary (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_num        VARCHAR(16)   NOT NULL,
    acct_id         BIGINT,
    cust_id         BIGINT,
    total_auth_amt  DECIMAL(12,2),
    auth_count      INTEGER,
    last_auth_ts    VARCHAR(26)
);
CREATE INDEX idx_auth_summary_card ON auth_summary(card_num);

-- IMS child segment PAUTDTL1 -> auth_details
CREATE TABLE auth_details (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_summary_id         BIGINT        NOT NULL,
    auth_ts                 VARCHAR(26),
    auth_type               VARCHAR(4),
    card_expiry_date        VARCHAR(4),
    message_type            VARCHAR(6),
    message_source          VARCHAR(6),
    auth_id_code            VARCHAR(6),
    auth_resp_code          VARCHAR(2),
    auth_resp_reason        VARCHAR(4),
    processing_code         VARCHAR(6),
    transaction_amt         DECIMAL(12,2),
    approved_amt            DECIMAL(12,2),
    merchant_category_code  VARCHAR(4),
    acqr_country_code       VARCHAR(3),
    pos_entry_mode          INTEGER,
    merchant_id             VARCHAR(15),
    merchant_name           VARCHAR(22),
    merchant_city           VARCHAR(13),
    merchant_state          VARCHAR(2),
    merchant_zip            VARCHAR(9),
    transaction_id          VARCHAR(15),
    CONSTRAINT fk_auth_details_summary FOREIGN KEY (auth_summary_id) REFERENCES auth_summary(id)
);

-- DB2 fraud table AUTHFRDS
CREATE TABLE authfrds (
    card_num                VARCHAR(16)   NOT NULL,
    auth_ts                 TIMESTAMP     NOT NULL,
    auth_type               VARCHAR(4),
    card_expiry_date        VARCHAR(4),
    message_type            VARCHAR(6),
    message_source          VARCHAR(6),
    auth_id_code            VARCHAR(6),
    auth_resp_code          VARCHAR(2),
    auth_resp_reason        VARCHAR(4),
    processing_code         VARCHAR(6),
    transaction_amt         DECIMAL(12,2),
    approved_amt            DECIMAL(12,2),
    merchant_category_code  VARCHAR(4),
    acqr_country_code       VARCHAR(3),
    pos_entry_mode          SMALLINT,
    merchant_id             VARCHAR(15),
    merchant_name           VARCHAR(22),
    merchant_city           VARCHAR(13),
    merchant_state          VARCHAR(2),
    merchant_zip            VARCHAR(9),
    transaction_id          VARCHAR(15),
    match_status            VARCHAR(1),
    auth_fraud              VARCHAR(1),
    fraud_rpt_date          DATE,
    acct_id                 DECIMAL(11),
    cust_id                 DECIMAL(9),
    PRIMARY KEY (card_num, auth_ts)
);

-- =====================================================
-- Phase 1: Optional Module - DB2 Transaction Types
-- =====================================================

CREATE TABLE transaction_type (
    tr_type         VARCHAR(2)    NOT NULL PRIMARY KEY,
    tr_description  VARCHAR(50)
);

CREATE TABLE transaction_type_category (
    trc_type_code       VARCHAR(2)  NOT NULL,
    trc_type_category   VARCHAR(4)  NOT NULL,
    trc_cat_data        VARCHAR(50),
    PRIMARY KEY (trc_type_code, trc_type_category),
    CONSTRAINT fk_ttc_type FOREIGN KEY (trc_type_code) REFERENCES transaction_type(tr_type)
);
